//login section
export const LOGIN= 'LOGIN';
export const CHECK_IS_LOGIN= 'CHECK_IS_LOGIN';
export const LOGOUT= 'LOGOUT';
export const SETPREVPATH= 'SETPREVPATH';
export const RES_PENDING= 'RES_PENDING';
export const GET_INITIAL_DATA='GET_INITIAL_DATA';
export const GET_SELECTED = 'GET_SELECTED';
export const SET_CURRENT_SESSION = 'SET_CURRENT_SESSION'
export const SET_CURRENT_COURSE = 'SET_CURRENT_COURSE'
export const GET_ALL_DEPARTMENT_FOR_COURSE= 'GET_ALL_DEPARTMENT_FOR_COURSE';
export const ADD_DEPARTMENT= 'ADD_DEPARTMENT';
export const DELETE_DEPARTMENT= 'DELETE_DEPARTMENT';
export const EDIT_DEPARTMENT= 'EDIT_DEPARTMENT';
export const HIDE_SLACKBAR= 'HIDE_SLACKBAR';
export const CHANGE_SLACKBAR_MSG= 'CHANGE_SLACKBAR_MSG';
export const HANDLE_TAB_CHANGE= 'HANDLE_TAB_CHANGE';
export const PAGE_CHANGE= 'PAGE_CHANGE';