//login section
export const LOGIN= 'LOGIN';
export const CHECK_IS_LOGIN= 'CHECK_IS_LOGIN';
export const LOGOUT= 'LOGOUT';
export const GET_ALL_DEPARTMENT_FOR_COURSE= 'GET_ALL_DEPARTMENT_FOR_COURSE';
export const ADD_DEPARTMENT= 'ADD_DEPARTMENT';
export const DELETE_DEPARTMENT= 'DELETE_DEPARTMENT';
export const EDIT_DEPARTMENT= 'EDIT_DEPARTMENT';
export const HIDE_SLACKBAR= 'HIDE_SLACKBAR';
export const CHANGE_SLACKBAR_MSG= 'CHANGE_SLACKBAR_MSG';
export const HANDLE_TAB_CHANGE= 'HANDLE_TAB_CHANGE';
export const PAGE_CHANGE= 'PAGE_CHANGE';

